# Generated by Django 5.2.7 on 2025-12-02 16:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('osm_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('landmark_type', models.CharField(choices=[('tourism', 'Tourism'), ('historic', 'Historic'), ('amenity', 'Amenity'), ('leisure', 'Leisure'), ('shop', 'Shop'), ('restaurant', 'Restaurant')], max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('osm_tags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'landmarks_landmark',
                'indexes': [models.Index(fields=['landmark_type'], name='landmarks_l_landmar_1ab182_idx'), models.Index(fields=['category'], name='landmarks_l_categor_e4da7f_idx')],
            },
        ),
    ]
