# Generated by Django 5.2.7 on 2025-11-03 17:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('star_rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('price_range', models.CharField(choices=[('budget', '€ Budget'), ('moderate', '€€ Moderate'), ('luxury', '€€€ Luxury')], max_length=20)),
                ('amenities', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='cities.city')),
            ],
            options={
                'db_table': 'hotels_hotel',
                'indexes': [models.Index(fields=['city'], name='hotels_hote_city_id_09ce11_idx'), models.Index(fields=['star_rating'], name='hotels_hote_star_ra_e9d0d2_idx'), models.Index(fields=['price_range'], name='hotels_hote_price_r_9cac81_idx')],
            },
        ),
    ]
