---
- name: restart squid
  service:
    name: squid
    state: restarted

- name: restart smbd
  service:
    name: samba-ad-dc
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

