import type { FoodResult } from './types';

export type QuickMeal = FoodResult & {
  time: string;
};

export type QuickMealSection = {
  title: string;
  subtitle?: string;
  items: QuickMeal[];
};

/** Usual meal presets — nutrition is estimated per typical portion, not per 100g */
export const QUICK_MEALS: QuickMealSection[] = [
  {
    title: 'Morning',
    items: [
      {
        name: 'Coffee',
        time: '08:00',
        calories: 25,
        carbs: 2,
        sugar: 1,
        protein: 1,
        fat: 1,
        saturatedFat: 0.5,
        fiber: 0,
        salt: 0.05,
        nutriScore: 'A',
        servingSize: '1 cup with milk',
        per: 'serving',
      },
    ],
  },
  {
    title: 'Breakfast',
    subtitle: 'Usually around 11:15',
    items: [
      {
        name: 'Scrambled eggs & 2 toast',
        time: '11:15',
        calories: 340,
        carbs: 30,
        sugar: 3,
        protein: 17,
        fat: 16,
        saturatedFat: 5,
        fiber: 2,
        salt: 1.2,
        nutriScore: 'B',
        servingSize: '2 eggs + 2 slices',
        per: 'serving',
      },
      {
        name: 'Scrambled eggs',
        time: '11:15',
        calories: 180,
        carbs: 2,
        sugar: 1,
        protein: 12,
        fat: 14,
        saturatedFat: 4,
        fiber: 0,
        salt: 0.6,
        nutriScore: 'A',
        servingSize: '2 eggs',
        per: 'serving',
      },
      {
        name: '2 pieces toast',
        time: '11:15',
        calories: 160,
        carbs: 28,
        sugar: 2,
        protein: 5,
        fat: 2,
        saturatedFat: 0.5,
        fiber: 2,
        salt: 0.6,
        nutriScore: 'B',
        servingSize: '2 slices',
        per: 'serving',
      },
    ],
  },
  {
    title: 'Lunch',
    items: [
      {
        name: 'Fruit salad & Greek yogurt',
        time: '13:00',
        calories: 180,
        carbs: 24,
        sugar: 19,
        protein: 11,
        fat: 4,
        saturatedFat: 2,
        fiber: 2,
        salt: 0.1,
        nutriScore: 'A',
        servingSize: '1 bowl + 1 pot',
        per: 'serving',
      },
      {
        name: 'Fruit salad',
        time: '13:00',
        calories: 80,
        carbs: 18,
        sugar: 15,
        protein: 1,
        fat: 0,
        saturatedFat: 0,
        fiber: 2,
        salt: 0,
        nutriScore: 'A',
        servingSize: '1 bowl',
        per: 'serving',
      },
      {
        name: 'Greek yogurt',
        time: '13:00',
        calories: 100,
        carbs: 6,
        sugar: 4,
        protein: 10,
        fat: 4,
        saturatedFat: 2.5,
        fiber: 0,
        salt: 0.1,
        nutriScore: 'A',
        servingSize: '1 pot (~150g)',
        per: 'serving',
      },
    ],
  },
  {
    title: 'Dinner',
    items: [
      {
        name: 'Salad, chicken & beef gyozas',
        time: '18:30',
        calories: 460,
        carbs: 59,
        sugar: 4,
        protein: 22,
        fat: 14,
        saturatedFat: 4,
        fiber: 3,
        salt: 1.8,
        nutriScore: 'C',
        servingSize: 'Salad + 5 chicken + 5 beef',
        per: 'serving',
      },
      {
        name: 'Side salad',
        time: '18:30',
        calories: 40,
        carbs: 5,
        sugar: 3,
        protein: 2,
        fat: 1,
        saturatedFat: 0.2,
        fiber: 2,
        salt: 0.1,
        nutriScore: 'A',
        servingSize: '1 bowl',
        per: 'serving',
      },
      {
        name: 'Chicken gyozas',
        time: '18:30',
        calories: 200,
        carbs: 28,
        sugar: 1,
        protein: 10,
        fat: 6,
        saturatedFat: 1.5,
        fiber: 1,
        salt: 0.9,
        nutriScore: 'C',
        servingSize: '5 pieces',
        per: 'serving',
      },
      {
        name: 'Beef gyozas',
        time: '18:30',
        calories: 220,
        carbs: 26,
        sugar: 1,
        protein: 12,
        fat: 8,
        saturatedFat: 3,
        fiber: 1,
        salt: 1,
        nutriScore: 'C',
        servingSize: '5 pieces',
        per: 'serving',
      },
    ],
  },
  {
    title: 'Indian favourites',
    items: [
      {
        name: 'Chicken tikka masala & rice',
        time: '18:30',
        calories: 480,
        carbs: 52,
        sugar: 6,
        protein: 28,
        fat: 14,
        saturatedFat: 5,
        fiber: 3,
        salt: 1.5,
        nutriScore: 'C',
        servingSize: '1 plate',
        per: 'serving',
      },
      {
        name: 'Lamb curry & rice',
        time: '18:30',
        calories: 520,
        carbs: 48,
        sugar: 4,
        protein: 26,
        fat: 18,
        saturatedFat: 7,
        fiber: 2,
        salt: 1.4,
        nutriScore: 'D',
        servingSize: '1 plate',
        per: 'serving',
      },
      {
        name: 'Dal & rice',
        time: '18:30',
        calories: 360,
        carbs: 58,
        sugar: 2,
        protein: 14,
        fat: 6,
        saturatedFat: 1,
        fiber: 8,
        salt: 0.8,
        nutriScore: 'A',
        servingSize: '1 plate',
        per: 'serving',
      },
      {
        name: 'Vegetable curry & rice',
        time: '18:30',
        calories: 400,
        carbs: 52,
        sugar: 8,
        protein: 10,
        fat: 12,
        saturatedFat: 3,
        fiber: 6,
        salt: 1,
        nutriScore: 'B',
        servingSize: '1 plate',
        per: 'serving',
      },
      {
        name: 'Chicken biryani',
        time: '18:30',
        calories: 450,
        carbs: 55,
        sugar: 3,
        protein: 22,
        fat: 12,
        saturatedFat: 4,
        fiber: 2,
        salt: 1.2,
        nutriScore: 'C',
        servingSize: '1 plate',
        per: 'serving',
      },
      {
        name: 'Naan bread',
        time: '18:30',
        calories: 260,
        carbs: 45,
        sugar: 3,
        protein: 8,
        fat: 5,
        saturatedFat: 1,
        fiber: 2,
        salt: 1,
        nutriScore: 'C',
        servingSize: '1 naan',
        per: 'serving',
      },
      {
        name: 'Samosas (2)',
        time: '18:30',
        calories: 240,
        carbs: 26,
        sugar: 2,
        protein: 6,
        fat: 12,
        saturatedFat: 4,
        fiber: 3,
        salt: 0.8,
        nutriScore: 'D',
        servingSize: '2 pieces',
        per: 'serving',
      },
    ],
  },
];
