# enterprise-pentest-lab Ansible inventory
# Host-only network 192.168.56.0/24

[kali]
kali-attacker ansible_host=192.168.56.10 ansible_user=vagrant ansible_ssh_private_key_file=../.vagrant/machines/kali-attacker/virtualbox/private_key

[ubuntu_target]
ubuntu-target ansible_host=192.168.56.20 ansible_user=vagrant ansible_ssh_private_key_file=../.vagrant/machines/ubuntu-target/virtualbox/private_key

[windows_server]
windows-server ansible_host=192.168.56.30 ansible_user=vagrant ansible_ssh_private_key_file=../.vagrant/machines/windows-server/virtualbox/private_key

[lab:children]
kali
ubuntu_target
windows_server
